/*
 * PharmaCX Intelligence — Phase 0: Infrastructure Setup
 *
 * Prerequisites: ACCOUNTADMIN role, Phase 1 Drug Safety Co-Pilot deployed
 *
 * This script creates:
 *   - CX_RAW, CX_BRONZE, CX_SILVER, CX_GOLD schemas
 *   - Internal stages for call recordings (MP3/WAV) and HCP videos (MP4)
 *   - CX_AGENT_SUPERVISOR and CX_QUALITY_ANALYST roles
 *   - RBAC grants following least-privilege model
 */

USE DATABASE PHARMACOVIGILANCE;
USE WAREHOUSE PV_WH;

-- ============================================================
-- Step CX-0.1: Create CX Schemas (Medallion Architecture)
-- ============================================================
CREATE SCHEMA IF NOT EXISTS PHARMACOVIGILANCE.CX_RAW;
CREATE SCHEMA IF NOT EXISTS PHARMACOVIGILANCE.CX_BRONZE;
CREATE SCHEMA IF NOT EXISTS PHARMACOVIGILANCE.CX_SILVER;
CREATE SCHEMA IF NOT EXISTS PHARMACOVIGILANCE.CX_GOLD;

-- ============================================================
-- Step CX-0.2: Create Internal Stages
-- SSE encryption + directory listing for TO_FILE() access
-- ============================================================
CREATE STAGE IF NOT EXISTS CX_RAW.CALL_RECORDING_STAGE
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
    DIRECTORY = (ENABLE = TRUE);

CREATE STAGE IF NOT EXISTS CX_RAW.HCP_VIDEO_STAGE
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
    DIRECTORY = (ENABLE = TRUE);

-- ============================================================
-- Step CX-0.3: Create CX Roles
-- CX_AGENT_SUPERVISOR: compliance views only (CX_GOLD)
-- CX_QUALITY_ANALYST: full read across bronze/silver/gold
-- ============================================================
CREATE ROLE IF NOT EXISTS CX_AGENT_SUPERVISOR;
CREATE ROLE IF NOT EXISTS CX_QUALITY_ANALYST;

-- Role hierarchy — both report to ACCOUNTADMIN
GRANT ROLE CX_AGENT_SUPERVISOR TO ROLE ACCOUNTADMIN;
GRANT ROLE CX_QUALITY_ANALYST TO ROLE ACCOUNTADMIN;

-- ============================================================
-- Step CX-0.4: Database & Warehouse Access for New Roles
-- ============================================================
GRANT USAGE ON DATABASE PHARMACOVIGILANCE TO ROLE CX_AGENT_SUPERVISOR;
GRANT USAGE ON DATABASE PHARMACOVIGILANCE TO ROLE CX_QUALITY_ANALYST;
GRANT USAGE ON WAREHOUSE PV_WH TO ROLE CX_AGENT_SUPERVISOR;
GRANT USAGE ON WAREHOUSE PV_WH TO ROLE CX_QUALITY_ANALYST;

-- ============================================================
-- Step CX-0.5: CX_AGENT_SUPERVISOR Grants
-- Gold schema only — compliance dashboards and triage views
-- ============================================================
GRANT USAGE ON SCHEMA PHARMACOVIGILANCE.CX_GOLD TO ROLE CX_AGENT_SUPERVISOR;
GRANT SELECT ON ALL VIEWS IN SCHEMA PHARMACOVIGILANCE.CX_GOLD TO ROLE CX_AGENT_SUPERVISOR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMACOVIGILANCE.CX_GOLD TO ROLE CX_AGENT_SUPERVISOR;

-- ============================================================
-- Step CX-0.6: CX_QUALITY_ANALYST Grants
-- Bronze + Silver + Gold — full read for quality investigations
-- ============================================================
GRANT USAGE ON SCHEMA PHARMACOVIGILANCE.CX_BRONZE TO ROLE CX_QUALITY_ANALYST;
GRANT USAGE ON SCHEMA PHARMACOVIGILANCE.CX_SILVER TO ROLE CX_QUALITY_ANALYST;
GRANT USAGE ON SCHEMA PHARMACOVIGILANCE.CX_GOLD TO ROLE CX_QUALITY_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA PHARMACOVIGILANCE.CX_BRONZE TO ROLE CX_QUALITY_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA PHARMACOVIGILANCE.CX_SILVER TO ROLE CX_QUALITY_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA PHARMACOVIGILANCE.CX_GOLD TO ROLE CX_QUALITY_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA PHARMACOVIGILANCE.CX_GOLD TO ROLE CX_QUALITY_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PHARMACOVIGILANCE.CX_BRONZE TO ROLE CX_QUALITY_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PHARMACOVIGILANCE.CX_SILVER TO ROLE CX_QUALITY_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PHARMACOVIGILANCE.CX_GOLD TO ROLE CX_QUALITY_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMACOVIGILANCE.CX_GOLD TO ROLE CX_QUALITY_ANALYST;

-- ============================================================
-- Step CX-0.7: DATA_ENGINEER Grants on CX Schemas
-- Read/write on RAW + Bronze + Silver (pipeline operator)
-- ============================================================
GRANT USAGE ON SCHEMA PHARMACOVIGILANCE.CX_RAW TO ROLE DATA_ENGINEER;
GRANT USAGE ON SCHEMA PHARMACOVIGILANCE.CX_BRONZE TO ROLE DATA_ENGINEER;
GRANT USAGE ON SCHEMA PHARMACOVIGILANCE.CX_SILVER TO ROLE DATA_ENGINEER;
GRANT CREATE TABLE ON SCHEMA PHARMACOVIGILANCE.CX_RAW TO ROLE DATA_ENGINEER;
GRANT CREATE TABLE ON SCHEMA PHARMACOVIGILANCE.CX_BRONZE TO ROLE DATA_ENGINEER;
GRANT CREATE TABLE ON SCHEMA PHARMACOVIGILANCE.CX_SILVER TO ROLE DATA_ENGINEER;
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA PHARMACOVIGILANCE.CX_RAW TO ROLE DATA_ENGINEER;
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA PHARMACOVIGILANCE.CX_BRONZE TO ROLE DATA_ENGINEER;
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA PHARMACOVIGILANCE.CX_SILVER TO ROLE DATA_ENGINEER;

-- ============================================================
-- Step CX-0.8: DRUG_SAFETY_OFFICER Grants on CX Schemas
-- All privileges — owns the pharmacovigilance data
-- ============================================================
GRANT ALL PRIVILEGES ON SCHEMA PHARMACOVIGILANCE.CX_RAW TO ROLE DRUG_SAFETY_OFFICER;
GRANT ALL PRIVILEGES ON SCHEMA PHARMACOVIGILANCE.CX_BRONZE TO ROLE DRUG_SAFETY_OFFICER;
GRANT ALL PRIVILEGES ON SCHEMA PHARMACOVIGILANCE.CX_SILVER TO ROLE DRUG_SAFETY_OFFICER;
GRANT ALL PRIVILEGES ON SCHEMA PHARMACOVIGILANCE.CX_GOLD TO ROLE DRUG_SAFETY_OFFICER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PHARMACOVIGILANCE.CX_RAW TO ROLE DRUG_SAFETY_OFFICER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PHARMACOVIGILANCE.CX_BRONZE TO ROLE DRUG_SAFETY_OFFICER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PHARMACOVIGILANCE.CX_SILVER TO ROLE DRUG_SAFETY_OFFICER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PHARMACOVIGILANCE.CX_GOLD TO ROLE DRUG_SAFETY_OFFICER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMACOVIGILANCE.CX_GOLD TO ROLE DRUG_SAFETY_OFFICER;

-- ============================================================
-- Step CX-0.9: PV_ANALYST Grants on CX Schemas
-- Read-only on Silver + Gold (masked PHI)
-- ============================================================
GRANT USAGE ON SCHEMA PHARMACOVIGILANCE.CX_SILVER TO ROLE PV_ANALYST;
GRANT USAGE ON SCHEMA PHARMACOVIGILANCE.CX_GOLD TO ROLE PV_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA PHARMACOVIGILANCE.CX_SILVER TO ROLE PV_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA PHARMACOVIGILANCE.CX_GOLD TO ROLE PV_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA PHARMACOVIGILANCE.CX_GOLD TO ROLE PV_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PHARMACOVIGILANCE.CX_SILVER TO ROLE PV_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PHARMACOVIGILANCE.CX_GOLD TO ROLE PV_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMACOVIGILANCE.CX_GOLD TO ROLE PV_ANALYST;

-- ============================================================
-- Step CX-0.10: Verification
-- ============================================================
SHOW SCHEMAS IN DATABASE PHARMACOVIGILANCE;

SHOW STAGES IN SCHEMA CX_RAW;

SHOW ROLES LIKE 'CX_%';
